Endpoint user backend andrea
Apacheco82/Jobs-Hood pull request #20
Opened 2023-04-21 12:31 UTC by Hedonista17

Usuario Empleado registro en funcionamiento 
Creacion  de archivo funcions.py para uso global de la api
Creacion de funciones en User.py para creacion del resto de usuarios (abogados y empresas)

2023-04-21 12:38 UTC, rlence requested changes

2023-04-21 12:38 UTC, rlence commented on src/api/domain/user/repository.py
> +    user_by_role = User(user_name,password,name,last_name,email)
no entiendo que quieres hacer con esto? no estas haciendo nada realmente

2023-04-21 13:07 UTC, Hedonista17 commented on src/api/domain/user/repository.py
> +    user_by_role = User(user_name,password,name,last_name,email)
En  el domain de user tenemos dos partes una es para crear unicamente el usuario "normal" que seria el usuario Worker con ello van enlazados el repositoyr-controller y route para poder crear dicho usuario en concreto. Esto ya le probado en la API de postman y lo hace correcto. 
Respecto a create_user_by_role es una funcion que actualmente no esta haciendo nada, es cierto pero esto es por que esta es la que se va a usar para poder crear los usuarios "lawyer" y los usuarios" Company". La he dejado ahi por que despues el resto de mis compañeros la tienen que usar.

2023-04-21 13:49 UTC, rlence commented on src/api/domain/user/repository.py
> +    user_by_role = User(user_name,password,name,last_name,email)
entonces que la creen cuando la necesiten si no hace nada, ps no hace nada no hace falta tenerlo

2023-04-21 14:07 UTC, Hedonista17 commented on src/api/domain/user/repository.py
> +    user_by_role = User(user_name,password,name,last_name,email)
creo que ya esta quitado todo lo referente a create user by role

2023-04-22 08:29 UTC, rlence approved these changes

2023-04-22 09:05 UTC, merged